name: Angular Snyk Scan

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build --prod

  snyk-scan:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Snyk Authentication
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Scan
      run: snyk test --json > snyk-report.json

  code-scanning-upload:
    runs-on: ubuntu-latest

    needs: snyk-scan

    steps:
    - name: Upload Snyk Results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-report.json
